version: '3'
services:
  backend:
    build: contact_book/.
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./contact_book:/backend
    expose:
      - 8000
    ports:
      - "8000:8000"
  frontend:
    build: contact_book_ui/.
    command: npm start
    volumes:
      - ./contact_book_ui:/frontend
    expose:
      - 80
    ports:
      - "80:3000"
    links:
      - backend

