# Generated by Django 3.2 on 2021-04-18 05:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
